import type { NextPage } from "next";
import Head from "next/head";
import { NavigationButton } from "../components/NavigationButton";
import { User } from "../components/User";
import {
  BsBoxArrowDownLeft,
  BsBoxArrowUpRight,
  BsFillBellFill,
} from "react-icons/bs";
import { Tabs } from "../components/Tabs";
import { AllWallets } from "../components/AllWallets";
import { Transactions } from "../components/Transactions";
import { Popup } from "../components/Popup";
import { useState } from "react";

const Home: NextPage = () => {
  const mainTabs = ["My Wallet", "Report", "Settings"];
  const [isPopupOpen, setIsPopupOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Be Earning</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-5">
        <div className="flex items-center justify-between">
          <User />
          <div className="flex gap-[6px]">
            <NavigationButton Icon={BsBoxArrowUpRight} />
            <NavigationButton Icon={BsBoxArrowDownLeft} />
            <NavigationButton Icon={BsFillBellFill} />
          </div>
        </div>
        <section className="pb-4">
          <Tabs tabsData={mainTabs} />
          <AllWallets />
        </section>
        <section id="transactions">
          <Transactions />
        </section>
        <section>
          <Popup isPopupOpen={isPopupOpen} setIsPopupOpen={setIsPopupOpen} />
        </section>
      </main>
    </>
  );
};

export default Home;
