import type { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import type { TArr } from "../../../types";
import { BsChevronLeft } from "react-icons/bs";
import { get24SeedWords } from "../../utils/getData";
import { AllSeedWords } from "../../components/AllSeedWords";
import { CopySection } from "../../components/CopySection";

const CreateNewWalletPage = ({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Create New Wallet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center gap-2 px-5 py-4">
        <nav>
          <Link href={"/"}>
            <BsChevronLeft />
          </Link>
        </nav>
        <h1 className="font-semibold capitalize">Create new wallet</h1>
      </header>
      <main className="min-h-screen bg-[#F9FBFF] px-5">
        <h2 className="capitalize text-accent-blue-1">Auto Gen Seed Phrase?</h2>
        <section id="all-seed-words">
          <AllSeedWords allSeedWords={data} />
        </section>
        <section>
          <CopySection />
        </section>
      </main>
    </>
  );
};

export default CreateNewWalletPage;

export const getServerSideProps: GetServerSideProps<{
  data: TArr;
}> = async () => {
  const seedWords = await get24SeedWords();
  if (!seedWords) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: {
      data: seedWords,
    },
  };
};
