import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { BsChevronCompactDown } from "react-icons/bs";
import { FaStore } from "react-icons/fa";
import { FiMoreHorizontal } from "react-icons/fi";
import { BottomPagination } from "../../components/BottomPagination";
import { DApp } from "../../components/DApp";
import { NavigationButton } from "../../components/NavigationButton";
import { Search } from "../../components/Search";
import { Tabs } from "../../components/Tabs";

const DecentralizedPage: NextPage = () => {
  const decentralizedPageTabsData = [
    "Decentralized Application",
    "Smart contract",
  ];

  return (
    <>
      <Head>
        <title>Applications</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-[#F9FBFF] px-5">
        <section className="grid w-full grid-cols-3 items-center justify-between">
          <div className="col-start-2 flex justify-center">
            <Link
              href="/"
              className="inline-flex items-center justify-center rounded-full border p-1 text-center shadow-xl"
            >
              <BsChevronCompactDown className="h-7 w-7" />
            </Link>
          </div>
          <div className="col-start-3 flex justify-end gap-[6px]">
            <NavigationButton Icon={FaStore} />
            <NavigationButton Icon={FiMoreHorizontal} />
          </div>
        </section>
        <Tabs tabsData={decentralizedPageTabsData} />
        <section>
          <div className="grid w-full grid-cols-5 gap-x-1 gap-y-4 py-4 text-black">
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
            <DApp isMainPage={false} />
          </div>
        </section>
        <nav className="py-4">
          <BottomPagination />
        </nav>
        <section>
          <Search />
        </section>
      </main>
    </>
  );
};

export default DecentralizedPage;
